[package]
name = "leafish_blocks"
version = "0.0.1"
authors = [ "Thinkofdeath <thinkofdeath@spigotmc.org>" ]
edition = "2018"

[dependencies]
lazy_static = "1.4.0" # TODO: get rid of this and use OnceCell instead
cgmath = "0.17"
collision = "0.20"
parking_lot = "0.12"


[dependencies.leafish_shared]
path = "../shared"
version = "0"
