// This file was autogenerated by `generate_blocks`.
// Do not modify this file by hand.

use crate::Block;
use shared::Version;

pub mod legacy;
mod v1_13;
mod v1_13_2;
mod v1_14_4;
mod v1_15_2;
mod v1_16_1;
mod v1_16_5;
mod v1_17_1;
mod v1_18_2;
mod v1_19;

pub fn get_block_mapping(version: Version) -> &'static [Block] {
    match version {
        Version::V1_13 => v1_13::MAPPING,
        Version::V1_13_2 => v1_13_2::MAPPING,
        Version::V1_14 => v1_14_4::MAPPING,
        Version::V1_15 => v1_15_2::MAPPING,
        Version::V1_16 => v1_16_1::MAPPING,
        Version::V1_16_2 => v1_16_5::MAPPING,
        Version::V1_17 => v1_17_1::MAPPING,
        Version::V1_18 => v1_18_2::MAPPING,
        Version::V1_19 => v1_19::MAPPING,
        _ => unreachable!(),
    }
}
