name: Packaging
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: leafish.flatpak
        manifest-path: packaging/flatpak/com.github.Lea_fish.Leafish.yaml
        cache-key: flatpak-builder-${{ github.sha }}
